/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlay } from "@fortawesome/free-solid-svg-icons";
import { IconProp } from "@fortawesome/fontawesome-svg-core";
import { useState } from "react";
export default function PlayList() {
  const MainHead = dynamic(() => import("../../components/mainHead"));
  const NavItem = dynamic(() => import("../../components/navItem"));
  const Media = dynamic(() => import("../../components/media"));

  const Play = faPlay as IconProp;
  const [songs,setSongs] = useState([
        {
            name : 'End of time',
            singer: 'K-391,Alan Walker',
            image: '/song-image/end-of-time.jpg',
            album: 'US-UK',
            time: '03:08'
        },
        {
            name : 'Legends-Never-Die',
            singer: 'Jeff Danna',
            image: '/song-image/legend-never-die.jpg',
            time: '04:20'
        },
        {
            name : 'Please-Don-t-Go',
            singer: 'Joel-Adams',
            image: '/song-image/please-dont-go.jpg',
            time: '03:24'
        },
        {
            name : 'See-You-Again',
            singer: 'Wiz-Khalifa,Charlie-Puth',
            image: '/song-image/see-you-again.jpg',
            time: '03:46'
        },
        {
            name : 'Cưới Thôi',
            singer: 'Massew',
            image: '/song-image/cuoi-thoi.jpg',
            time: '04:12'
        },
        {
            name : 'Yêu Là Cưới',
            singer: 'Phát Hồ,X2X',
            image: '/song-image/yeu-la-cuoi.jpg',
            time: '03:23'
        },
        {
          name : 'End of time',
          singer: 'K-391,Alan Walker',
          image: '/song-image/end-of-time.jpg',
          time: '03:42'
      },
      {
          name : 'Legends-Never-Die',
          singer: 'Jeff Danna',
          image: '/song-image/legend-never-die.jpg',
          time: '03:36'
      },
      {
          name : 'Please-Don-t-Go',
          singer: 'Joel-Adams',
          image: '/song-image/please-dont-go.jpg',
          time: '03:42'
      },
      {
          name : 'See-You-Again',
          singer: 'Wiz-Khalifa,Charlie-Puth',
          image: '/song-image/see-you-again.jpg',
          time: '03:12'
      },
      {
          name : 'Cưới Thôi',
          singer: 'Massew',
          image: '/song-image/cuoi-thoi.jpg',
          time: '04:18'
      },
      {
          name : 'Yêu Là Cưới',
          singer: 'Phát Hồ,X2X',
          image: '/song-image/yeu-la-cuoi.jpg',
          time: '04:26'
      }
  ])
  return (
    <>
      <Head>
        <title>MP3 | Nghe tải nhạc hay chất lượng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex">
        <section className="flex-1 bg-[#170f23] ml-[240px]">
          <MainHead />
          <div className="flex px-[60px] text-white text-center pb-[120px]">
            <div className="w-[300px] mr-[40px]">
              <div className="w-[300px] h-[300px] overflow-hidden rounded-[8px]">
                <img
                  src="/audio_default.png"
                  className="w-[100%] h-[100%] hover:scale-105 transition-[500ms]"
                  alt=""
                ></img>
              </div>
              <p className=" text-[20px] font-bold mt-[8px] ">Playlist #1</p>
              <p className="text-[12px] text-[#FFFFFF80]">
                Tạo bởi <span className="text-white">Nguyễn Mạnh Dũng</span>
              </p>
              <p className="text-[12px] text-[#FFFFFF80]">Công khai</p>

              <Link href="/">
                <a className="flex ml-[50%] translate-x-[-50%] items-center justify-center uppercase bg-[#7200a1] my-[20px] py-[9px] rounded-[16px]">
                  <span className="mr-[8px]">
                    <FontAwesomeIcon
                      icon={Play}
                      className="w-[16px] h-[16px]"
                    />
                  </span>
                  Phát tất cả
                </a>
              </Link>
            </div>
            <div className="flex-1 p-[10px]">
              <div className="text-[#FFFFFF80] uppercase flex justify-between text-[12px]">
                <span>Bài hát</span>
                <span>Album</span>
                <span>Thời Gian</span>
              </div>
              <ul className="mt-[12px] last:border-b-[0.5px] border-[#FFFFFF80]">
                {songs.map((item, index) => (
                  <Link key={index} href="">
                    <a>
                      <li className="flex  justify-between items-center p-[10px] text-[12px] text-[#FFFFFF80] border-t-[0.5px] border-[#ffffff80]">
                        <div className="flex items-center ml-[-8px]">
                          <img
                            src={item.image}
                            className="w-[40px] h-[40px]"
                          ></img>
                          <div className="ml-[8px] flex flex-col">
                            <p className="text-[14px] text-left text-white">{item.name}</p>
                            <p className="hover:text-[#7200a1] hover:underline">{item.singer}</p>
                          </div>
                        </div>
                        {item?.album && <p className="ml-[-120px] hover:text-[#7200a1] hover:underline">{item?.album}</p>}
                        <p>{item.time}</p>
                      </li>
                    </a>
                  </Link>
                ))}
              </ul>
            </div>
          </div>
        </section>
        <NavItem />
        <Media />
      </div>
    </>
  );
}
