/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMusic,faChartLine,faPlus } from "@fortawesome/free-solid-svg-icons";
import { faDotCircle,faStar } from "@fortawesome/fontawesome-free-regular";
import { IconProp } from "@fortawesome/fontawesome-svg-core";
import Link from "next/link";
import { useRef,useEffect } from "react";
import dynamic from "next/dynamic";

export default function Home() {

  const MainPage = dynamic(() =>
  import('../components/main')
)
const Media = dynamic(() =>
  import('../components/media')
)
const NavItem = dynamic(() =>
  import('../components/navItem')
)

  return (
    <>
      <Head>
        <title>MP3 | Nghe tải nhạc hay chất lượng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex">
        
        <section className="flex-1 bg-[#170f23] ml-[240px]"> 
                <MainPage />
        </section>
        <NavItem />
        <Media />
      </div>
    </>
  );
}
